[profile]
research_interests = ["Computer Vision", "Natural Language Processing"]

spotlight = [
  "Started working on AI Financial Advisor [SenFAI](/projects/senfai/).",
  "I will be presenting my project on Kaggle AI competition this September."
]
